name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download zig
        run: wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz

      - name: Extract
        run: tar -xf zig-linux-x86_64-0.13.0.tar.xz

      - name: Alias
        run: alias zig=$PWD/zig-linux-x86_64-0.13.0/zig

      - name: Version
        run: $PWD/zig-linux-x86_64-0.13.0/zig version

      - name: Test
        run: $PWD/zig-linux-x86_64-0.13.0/zig build test
